# version format
version: 1.0.1.{build}

# Do not build on tags
skip_tags: true


build_script:
  - cd BuildPackages
  - Package.build.cmd

artifacts:
  - path: Releases\*.nupkg
  - path: Releases\*.zip
  
deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: aaa28126-b4d8-4431-8b5a-2b914155e8b7
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/